#!/bin/bash
#
# Quick Usage Guide for Report Generation and XAI Analysis Scripts
# ================================================================
#
# This script demonstrates how to use the report generators and
# explainable AI analysis tools for your DETR and DETR-HYBRID-V2 models.
#
# Make this executable: chmod +x usage_examples.sh
# Run examples: bash usage_examples.sh
#

set -e

PROJECT_DIR="/root/fire-and-smoke-detection-thesis"
DETR_DIR="$PROJECT_DIR/code/DETR"
DETR_HYBRID_V2_DIR="$PROJECT_DIR/code/DETR-HYBRID-V2"

echo "========================================================================"
echo "  DETR & DETR-HYBRID-V2 Report Generation & XAI Analysis Examples"
echo "========================================================================"
echo ""

# ========================================================================
# SECTION 1: REPORT GENERATION - DETR
# ========================================================================
echo "SECTION 1: Generate Excel Report for DETR Model"
echo "------------------------------------------------------------------------"
echo ""
echo "Command:"
echo "-------"
echo "python $DETR_DIR/util/report_generator.py \\"
echo "    --output_dir $DETR_DIR/outputs \\"
echo "    --experiment_name \"Pretrained-2\""
echo ""
echo "Description:"
echo "-----------"
echo "Generates a comprehensive Excel report with detection metrics, per-class"
echo "metrics, loss components, and training curves for the DETR Pretrained-2"
echo "experiment."
echo ""
echo "Output: $DETR_DIR/outputs/Pretrained-2/report_YYYYMMDD_HHMMSS.xlsx"
echo ""
echo "To execute this command, run:"
echo "cd $PROJECT_DIR"
echo "python code/DETR/util/report_generator.py --output_dir code/DETR/outputs --experiment_name \"Pretrained-2\""
echo ""
echo "========================================================================"
echo ""

# ========================================================================
# SECTION 2: REPORT GENERATION - ALL DETR VARIANTS
# ========================================================================
echo "SECTION 2: Generate Reports for All DETR Variants"
echo "------------------------------------------------------------------------"
echo ""
echo "Generate reports for comparison:"
echo ""

echo "1. Pretrained (ResNet50):"
echo "   python code/DETR/util/report_generator.py --output_dir code/DETR/outputs --experiment_name \"Pretrained\""
echo ""

echo "2. Pretrained-2 (variant 2):"
echo "   python code/DETR/util/report_generator.py --output_dir code/DETR/outputs --experiment_name \"Pretrained-2\""
echo ""

echo "3. From Scratch (no pretraining):"
echo "   python code/DETR/util/report_generator.py --output_dir code/DETR/outputs --experiment_name \"from_scratch\""
echo ""

echo "After generating all reports, you can compare metrics across experiments"
echo "by copying Summary rows into a comparison table."
echo ""
echo "========================================================================"
echo ""

# ========================================================================
# SECTION 3: REPORT GENERATION - DETR-HYBRID-V2
# ========================================================================
echo "SECTION 3: Generate Excel Report for DETR-HYBRID-V2 Model"
echo "------------------------------------------------------------------------"
echo ""
echo "Command:"
echo "-------"
echo "python $DETR_HYBRID_V2_DIR/util/report_generator.py \\"
echo "    --output_dir $DETR_HYBRID_V2_DIR/outputs \\"
echo "    --experiment_name \"2-withwarmingepoch\""
echo ""
echo "Description:"
echo "-----------"
echo "Generates a comprehensive Excel report including:"
echo "  • Detection metrics (AP/AR across IoU levels)"
echo "  • Per-class metrics (Fire/Smoke)"
echo "  • Efficiency metrics (inference time, GFLOPs)"
echo "  • Pruning metrics (pixel keep ratio, token reduction)"
echo "  • Training curves with epoch-wise efficiency stats"
echo ""
echo "Output: $DETR_HYBRID_V2_DIR/outputs/2-withwarmingepoch/report_YYYYMMDD_HHMMSS.xlsx"
echo ""
echo "To execute this command, run:"
echo "cd $PROJECT_DIR"
echo "python code/DETR-HYBRID-V2/util/report_generator.py --output_dir code/DETR-HYBRID-V2/outputs --experiment_name \"2-withwarmingepoch\""
echo ""
echo "========================================================================"
echo ""

# ========================================================================
# SECTION 4: REPORT GENERATION - ALL DETR-HYBRID-V2 VARIANTS
# ========================================================================
echo "SECTION 4: Generate Reports for All DETR-HYBRID-V2 Variants"
echo "------------------------------------------------------------------------"
echo ""
echo "Generate reports for different pruning configurations:"
echo ""

echo "1. Initial experiment:"
echo "   python code/DETR-HYBRID-V2/util/report_generator.py --output_dir code/DETR-HYBRID-V2/outputs --experiment_name \"1\""
echo ""

echo "2. With warming epoch (optimized):"
echo "   python code/DETR-HYBRID-V2/util/report_generator.py --output_dir code/DETR-HYBRID-V2/outputs --experiment_name \"2-withwarmingepoch\""
echo ""

echo "After generating reports, compare:"
echo "  • Impact of warming epoch on model performance"
echo "  • Pruning effectiveness (pixel keep ratio)"
echo "  • Inference speedup vs accuracy trade-off"
echo ""
echo "========================================================================"
echo ""

# ========================================================================
# SECTION 5: EXPLAINABLE AI ANALYSIS - DETR-HYBRID-V2
# ========================================================================
echo "SECTION 5: Run Explainable AI Analysis for DETR-HYBRID-V2"
echo "------------------------------------------------------------------------"
echo ""
echo "Command (GPU):"
echo "-------------"
echo "python $DETR_HYBRID_V2_DIR/util/explainable_ai.py \\"
echo "    --model_path $DETR_HYBRID_V2_DIR/outputs/2-withwarmingepoch/checkpoint.pth \\"
echo "    --output_dir $DETR_HYBRID_V2_DIR/outputs/2-withwarmingepoch \\"
echo "    --num_samples 10 \\"
echo "    --device cuda"
echo ""
echo "Command (CPU):"
echo "-------------"
echo "python $DETR_HYBRID_V2_DIR/util/explainable_ai.py \\"
echo "    --model_path $DETR_HYBRID_V2_DIR/outputs/2-withwarmingepoch/checkpoint.pth \\"
echo "    --output_dir $DETR_HYBRID_V2_DIR/outputs/2-withwarmingepoch \\"
echo "    --num_samples 5 \\"
echo "    --device cpu"
echo ""
echo "Description:"
echo "-----------"
echo "Generates comprehensive explainability analysis including:"
echo ""
echo "  1. Pruning Decision Visualization"
echo "     • Before/after pruning comparisons"
echo "     • Shows which regions are preserved vs pruned"
echo "     • Verifies correctness of pruning decisions"
echo ""
echo "  2. Attention Pattern Analysis"
echo "     • Decoder cross-attention heatmaps"
echo "     • Shows which image regions the model attends to"
echo "     • Multiple query object visualizations"
echo ""
echo "  3. Feature Importance Analysis"
echo "     • Per-layer importance scores"
echo "     • Identifies critical transformer layers"
echo "     • Charts showing importance distribution"
echo ""
echo "  4. Decoder Efficiency Analysis"
echo "     • Token utilization statistics"
echo "     • Comparison of kept vs. pruned token importance"
echo "     • Accuracy/efficiency trade-off quantification"
echo ""
echo "Output Directory:"
echo "  $DETR_HYBRID_V2_DIR/outputs/2-withwarmingepoch/xai_analysis/"
echo ""
echo "Generated files:"
echo "  • before_after_*.png          - Pruning visualizations"
echo "  • attention_heatmap_*.png     - Attention patterns"
echo "  • feature_importance_chart.png - Layer importance"
echo "  • *.csv files                 - Quantitative metrics"
echo "  • summary_report.json         - Analysis summary"
echo ""
echo "To execute this command, run:"
echo "cd $PROJECT_DIR"
echo "python code/DETR-HYBRID-V2/util/explainable_ai.py \\"
echo "    --model_path code/DETR-HYBRID-V2/outputs/2-withwarmingepoch/checkpoint.pth \\"
echo "    --output_dir code/DETR-HYBRID-V2/outputs/2-withwarmingepoch \\"
echo "    --num_samples 10 \\"
echo "    --device cuda"
echo ""
echo "========================================================================"
echo ""

# ========================================================================
# SECTION 6: COMPLETE WORKFLOW
# ========================================================================
echo "SECTION 6: Complete Workflow for Thesis Writing"
echo "------------------------------------------------------------------------"
echo ""
echo "Step 1: Generate all experiment reports"
echo "-------"
echo "bash <<'EOF'"
echo "cd $PROJECT_DIR"
echo ""
echo "# DETR reports"
echo "python code/DETR/util/report_generator.py --output_dir code/DETR/outputs --experiment_name \"Pretrained-2\""
echo ""
echo "# DETR-HYBRID-V2 reports"
echo "python code/DETR-HYBRID-V2/util/report_generator.py --output_dir code/DETR-HYBRID-V2/outputs --experiment_name \"2-withwarmingepoch\""
echo "EOF"
echo ""
echo ""
echo "Step 2: Compare results in Excel"
echo "--------"
echo "1. Open: code/DETR/outputs/Pretrained-2/report_*.xlsx"
echo "2. Open: code/DETR-HYBRID-V2/outputs/2-withwarmingepoch/report_*.xlsx"
echo "3. Copy Summary rows into comparison table in your thesis"
echo ""
echo ""
echo "Step 3: Generate XAI analysis for model explanation"
echo "--------"
echo "cd $PROJECT_DIR"
echo "python code/DETR-HYBRID-V2/util/explainable_ai.py \\"
echo "    --model_path code/DETR-HYBRID-V2/outputs/2-withwarmingepoch/checkpoint.pth \\"
echo "    --output_dir code/DETR-HYBRID-V2/outputs/2-withwarmingepoch \\"
echo "    --num_samples 15 \\"
echo "    --device cuda"
echo ""
echo ""
echo "Step 4: Include XAI visualizations in thesis"
echo "--------"
echo "1. Review: xai_analysis/pruning_analysis/before_after_*.png"
echo "2. Review: xai_analysis/attention_analysis/attention_heatmap_*.png"
echo "3. Include best examples in 'Model Explainability' chapter"
echo ""
echo ""
echo "Step 5: Create model comparison table"
echo "--------"
echo "Combine Summary rows from both reports into a single comparison table"
echo "showing metrics side-by-side (DETR vs. DETR-HYBRID-V2)"
echo ""
echo "========================================================================"
echo ""

# ========================================================================
# SECTION 7: TROUBLESHOOTING
# ========================================================================
echo "SECTION 7: Troubleshooting & Tips"
echo "------------------------------------------------------------------------"
echo ""
echo "Issue: ModuleNotFoundError when running scripts"
echo "Solution:"
echo "  pip install torch torchvision pandas openpyxl matplotlib opencv-python"
echo ""
echo "Issue: CUDA out of memory for XAI analysis"
echo "Solution:"
echo "  Use --device cpu and reduce --num_samples"
echo "  Or use a machine with more GPU memory"
echo ""
echo "Issue: Report shows all zeros or empty cells"
echo "Possible causes:"
echo "  1. Experiment directory doesn't exist"
echo "  2. training_log.json or test_log.json is missing"
echo "  3. Incorrect experiment name (check exact folder name)"
echo ""
echo "Verify experiment exists:"
echo "  ls -la code/DETR/outputs/"
echo "  ls -la code/DETR-HYBRID-V2/outputs/"
echo ""
echo "========================================================================"
echo ""

# ========================================================================
# SECTION 8: METRICS REFERENCE
# ========================================================================
echo "SECTION 8: Metrics Reference Guide"
echo "------------------------------------------------------------------------"
echo ""
echo "DETECTION METRICS (Primary):"
echo "  • mAP50: Mean AP @ IoU=0.50 threshold"
echo "  • AP_fire: Fire class Average Precision"
echo "  • AP_smoke: Smoke class Average Precision"
echo "  • Recall_fire: Fire detection recall (sensitivity)"
echo "  • Recall_smoke: Smoke detection recall"
echo ""
echo "EFFICIENCY METRICS (DETR-HYBRID-V2 only):"
echo "  • Forward Time (ms): Inference latency"
echo "  • Imgs/sec: Throughput"
echo "  • Pixel Keep Ratio: Fraction of image tokens preserved (0-1)"
echo "  • GFLOPs (After): Computational cost after pruning"
echo ""
echo "LOSS COMPONENTS:"
echo "  • Total Loss: Sum of all losses"
echo "  • CE Loss: Classification (cross-entropy) loss"
echo "  • BBox Loss: Bounding box regression loss"
echo "  • GIoU Loss: Generalized IoU loss for boxes"
echo ""
echo "TRAINING METRICS:"
echo "  • Epochs Trained: Number of training epochs"
echo "  • Final Train Loss: Loss value at last epoch"
echo "  • Final Learning Rate: LR at final epoch"
echo "  • Model Parameters: Total trainable parameters"
echo ""
echo "========================================================================"
echo ""

echo "✓ Guide complete! Refer to README.md in each util/ directory for details."
echo ""
